# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ACoyOIYJQNmOkhMGBNCp_1hpemy7Zgp

Question 1
"""

n=int(input())
l=list(map(int,input().split()))
for i in l:
  if i%2==0:
    print(i,end=" ")

"""Question 2"""

n=int(input())
for i in range(1,n+1):
  print(" "*(n-i)+str(i)*i)