# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5zbDuE4Tf2MqxwykMa3fwzV2MIdL7lh

Question 1
"""

class Add():
  def __init__(self,a,b):
    self.a=a
    self.b=b
  def add(self,a,b):
    print(a+b)
m,n=map(int,input().split())
s=Add(m,n)
s.add(m,n)

"""Question 2"""

def swap(a,b):
  a,b=b,a
  return a,b  
m,n=map(int,input().split()) 
c,d=swap(m,n) 
print(c,d)