# -*- coding: utf-8 -*-
"""day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_748_eiW_D6ODDPYTMzwtDelUy_EXMdi

Question 1

Sorting Algorithm-Best-Average-Worst 

Bubble sort-o(n)-o(n^2)-o(n^2)
Insertion sort-o(n)-o(n^2)-o(n^2)
Selection sort-o(n^2)-o(n^2)-o(n^2)
Merge sort-o(nlog(n))-o(nlog(n))-o(nlog(n))
Quick sort-o(nlog(n))-o(nlog(n))-o(n^2)

Question 2
"""

a=list(map(int,input().split()))
for i in range(len(a)):
  m=i 
  for j in range(i+1,len(a)):
    if a[m]>a[j]:
      m=j 
    a[i],a[m]=a[m],a[i]
print("Sorted array",*a)

"""Question 3 """

def push(x):
  global l,top,size 
  if top==size-1:
    print("overflow")
    return 
  top+=1 
  l.insert(top,x)
def pop():
  global l,top,size 
  if top==-1:
    print("underflow")
    return 
  else:
    top-=1 
def display():
  if top==-1:
    print("underflow")
    return 
  for i in range(top,-1,-1):
    print(l[i])
l=list()
top=-1
size=5 
push(40)
push(30)
push(20)
pop()
display()

"""Question 4 """

def enqueue(x):
  global f,r 
  if r==size-1:
    print("Overflow")
    return 
  if r==-1:
    f=r=0 
  else:
    r+=1 
  l.insert(r,x)
def dequeue():
  global f,r 
  if f==r:
    print("underflow")
    f+=1
    return
  f+=1 
def display():
  global f,r
  if f==r+1:
    print("underflow")
    return 
  for i in range(f,r+1):
    print(l[i],end=" ")
  print()
l=list()
f=-1
r=-1 
size=5 
enqueue(10)
enqueue(20)
enqueue(30)
dequeue()
display()