# -*- coding: utf-8 -*-
"""day6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iBSA8-wcq-dlEgYchaTucZv7ojBPE4qk

Question 1
"""

l=input().split()
p=1
c=0 
for i in l:
  c=c+(len(i)-len(i.rstrip('0')))
  i=i.rstrip('0')
  p*=int(i)
print(str(p)+'0'*c)

"""Question 2"""

class MinStack:
  def __init__(self):
    self.stack=[]
    self.curr_min=None 
  def push(self,x):
    if self.curr_min==None:
      self.curr_min=x 
      self.stack.append(x)
    elif x>=self.curr_min:
      self.stack.append(x)
    elif x<self.curr_min:
      self.stack.append(2*x-self.curr_min)
      self.curr_min=x 
  def pop(self):
    x=self.stack.pop()
    if self.stack==[]:
      self.curr_min=None 
    elif x<self.curr_min:
      self.curr_min=2*self.curr_min-x 
  def top(self):
    return self.stack[-1]
  def getMin(self):
    return self.curr_min
m=MinStack()
m.push(30)
m.push(40)
m.push(20)
m.push(10)
print(m.getMin())